// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.1
// source: Lottery/lotterypb/lottery.proto

package lotterypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=First_name,json=FirstName,proto3" json:"First_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=Last_name,json=LastName,proto3" json:"Last_name,omitempty"`
	IdNumber  string `protobuf:"bytes,3,opt,name=Id_number,json=IdNumber,proto3" json:"Id_number,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Lottery_lotterypb_lottery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_Lottery_lotterypb_lottery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_Lottery_lotterypb_lottery_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Request) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Request) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketId int32 `protobuf:"varint,1,opt,name=Ticket_id,json=TicketId,proto3" json:"Ticket_id,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Lottery_lotterypb_lottery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_Lottery_lotterypb_lottery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_Lottery_lotterypb_lottery_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetTicketId() int32 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Lottery_lotterypb_lottery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_Lottery_lotterypb_lottery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_Lottery_lotterypb_lottery_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExistingCustomer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=First_name,json=FirstName,proto3" json:"First_name,omitempty" db:"first_name"`
	LastName  string `protobuf:"bytes,2,opt,name=Last_name,json=LastName,proto3" json:"Last_name,omitempty" db:"last_name"`
	IdNumber  string `protobuf:"bytes,3,opt,name=Id_number,json=IdNumber,proto3" json:"Id_number,omitempty" db:"id_number"`
}

func (x *ExistingCustomer) Reset() {
	*x = ExistingCustomer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Lottery_lotterypb_lottery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistingCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistingCustomer) ProtoMessage() {}

func (x *ExistingCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_Lottery_lotterypb_lottery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistingCustomer.ProtoReflect.Descriptor instead.
func (*ExistingCustomer) Descriptor() ([]byte, []int) {
	return file_Lottery_lotterypb_lottery_proto_rawDescGZIP(), []int{3}
}

func (x *ExistingCustomer) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ExistingCustomer) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ExistingCustomer) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

var File_Lottery_lotterypb_lottery_proto protoreflect.FileDescriptor

var file_Lottery_lotterypb_lottery_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2f, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x70, 0x62, 0x2f, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x22, 0x62, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x46, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x49, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x27,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x6b,
	0x0a, 0x10, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x46, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x49, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x49, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x4b, 0x0a, 0x0e, 0x4c,
	0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a,
	0x10, 0x42, 0x75, 0x79, 0x4c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x10, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2f, 0x6c, 0x6f, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x2f, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Lottery_lotterypb_lottery_proto_rawDescOnce sync.Once
	file_Lottery_lotterypb_lottery_proto_rawDescData = file_Lottery_lotterypb_lottery_proto_rawDesc
)

func file_Lottery_lotterypb_lottery_proto_rawDescGZIP() []byte {
	file_Lottery_lotterypb_lottery_proto_rawDescOnce.Do(func() {
		file_Lottery_lotterypb_lottery_proto_rawDescData = protoimpl.X.CompressGZIP(file_Lottery_lotterypb_lottery_proto_rawDescData)
	})
	return file_Lottery_lotterypb_lottery_proto_rawDescData
}

var file_Lottery_lotterypb_lottery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Lottery_lotterypb_lottery_proto_goTypes = []interface{}{
	(*Request)(nil),          // 0: lottery.Request
	(*Response)(nil),         // 1: lottery.Response
	(*Error)(nil),            // 2: lottery.Error
	(*ExistingCustomer)(nil), // 3: lottery.ExistingCustomer
}
var file_Lottery_lotterypb_lottery_proto_depIdxs = []int32{
	0, // 0: lottery.LotteryService.BuyLotteryTicket:input_type -> lottery.Request
	1, // 1: lottery.LotteryService.BuyLotteryTicket:output_type -> lottery.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Lottery_lotterypb_lottery_proto_init() }
func file_Lottery_lotterypb_lottery_proto_init() {
	if File_Lottery_lotterypb_lottery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Lottery_lotterypb_lottery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Lottery_lotterypb_lottery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Lottery_lotterypb_lottery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Lottery_lotterypb_lottery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistingCustomer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Lottery_lotterypb_lottery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Lottery_lotterypb_lottery_proto_goTypes,
		DependencyIndexes: file_Lottery_lotterypb_lottery_proto_depIdxs,
		MessageInfos:      file_Lottery_lotterypb_lottery_proto_msgTypes,
	}.Build()
	File_Lottery_lotterypb_lottery_proto = out.File
	file_Lottery_lotterypb_lottery_proto_rawDesc = nil
	file_Lottery_lotterypb_lottery_proto_goTypes = nil
	file_Lottery_lotterypb_lottery_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LotteryServiceClient is the client API for LotteryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LotteryServiceClient interface {
	BuyLotteryTicket(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type lotteryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryServiceClient(cc grpc.ClientConnInterface) LotteryServiceClient {
	return &lotteryServiceClient{cc}
}

func (c *lotteryServiceClient) BuyLotteryTicket(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/lottery.LotteryService/BuyLotteryTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotteryServiceServer is the server API for LotteryService service.
type LotteryServiceServer interface {
	BuyLotteryTicket(context.Context, *Request) (*Response, error)
}

// UnimplementedLotteryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLotteryServiceServer struct {
}

func (*UnimplementedLotteryServiceServer) BuyLotteryTicket(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyLotteryTicket not implemented")
}

func RegisterLotteryServiceServer(s *grpc.Server, srv LotteryServiceServer) {
	s.RegisterService(&_LotteryService_serviceDesc, srv)
}

func _LotteryService_BuyLotteryTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).BuyLotteryTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lottery.LotteryService/BuyLotteryTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).BuyLotteryTicket(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _LotteryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lottery.LotteryService",
	HandlerType: (*LotteryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuyLotteryTicket",
			Handler:    _LotteryService_BuyLotteryTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Lottery/lotterypb/lottery.proto",
}
